name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        USER: ${{secrets.DOCKER_USER}}
        PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $USER -p $PASSWORD
    - name: Build the Docker image and push
      run: find -iname "Dockerfile" -exec bash -c 'cd $(dirname $@) && docker pull ${{secrets.DOCKER_USER}}/openconnect:latest; docker build . --cache-from ${{secrets.DOCKER_USER}}/openconnect:latest --build-arg BUILDKIT_INLINE_CACHE=1 --file $(basename $@) -t ${{secrets.DOCKER_USER}}/openconnect:0.1.0 -t ${{secrets.DOCKER_USER}}/openconnect:latest && docker push ${{secrets.DOCKER_USER}}/openconnect -a' bash {} \;
